# Apache-httpd
version: '3.7'

services:
  apache:
    image: httpd:2.4
    hostname: apache-httpd
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "80:80"
    volumes:
      - '/usr/local/apache2/htdocs:/usr/local/apache2/htdocs'