# Suricata
version: '3.7'

services:
  suricata:
    image: jasonish/suricata:latest
    hostname: suricata
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    cap_add:
      - net_admin
      - net_raw
      - sys_nice
    network_mode: host
    volumes:
      - '/var/log/suricata:/var/log/suricata'
      - '/etc/suricata:/etc/suricata'
      - '/var/lib/suricata/rules/my.rule:/var/lib/suricata/rules/my.rule'
    environment:
      SURICATA_OPTIONS: "-i enp0s3"