# Zabbix server
version: '3.7'

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    init: true
    hostname: zabbix-server
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: 172.17.0.1
      DB_SERVER_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123Mudar@

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:latest
    init: true
    hostname: zabbix-web
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      DB_SERVER_HOST: 172.17.0.1
      DB_SERVER_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123Mudar@
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_HOST: 172.17.0.1
      ZBX_SERVER_PORT: 10051
      PHP_TZ: America/Sao_Paulo